ARG NODE_VERSION=14.18.1

FROM node:${NODE_VERSION} as build

WORKDIR /opt/frigate

COPY . .

RUN npm install --no-package-lock
RUN npm run build

FROM scratch

COPY --from=build /opt/frigate/build /build
